duty_list = ['emeraldex', 'faketitan', 'e9s', 'e10s', 'e11s', 'e12s', 'ucob', 'uwu', 'tea', 'e1', 'e2', 'e3', 'e4',
             'e5', 'e6', 'e7', 'e8', 'e9', 'e10', 'e11', 'e12', 'e1s', 'e2s', 'e3s', 'e4s', 'e5s', 'e6s', 'e7s', 'e8s',
             'o1-4', 'o5-8', 'o9-12', 'a1-4', 'a5-8', 'a9-12', 't1-5', 't6-9', 't10-13', 'nier1', 'nier2', 'alli50',
             'alli60', 'alli70', 'titania', 'inno', 'hades', 'ruby', 'wol', 'emerald', 'titaniaex', 'innoex', 'hadesex',
             'rubyex', 'varisex', 'wolex', 'fakeshiva', 'susano', 'lakshmi', 'shinryu', 'byakko', 'tsuku', 'rathalos',
             'suzaku', 'seiryu', 'gilgamesh3', 'lakshmiex', 'susanoex', 'shinryuex', 'byakkoex', 'tsukuex',
             'rathalosex', 'suzakuex', 'seiryuex', 'ravana', 'bismarck', 'thordan', 'nidhogg', 'sephirot', 'sophia',
             'zurvan', 'bismarckex', 'ravanaex', 'thordanex', 'nidhoggex', 'sephirotex', 'sophiaex', 'zurvanex',
             'nabriales', 'steps', 'chimera', 'hydra', 'gilgamesh1', 'ultros', 'gilgamesh2', 'ifrit', 'garuda', 'titan',
             'kingmog', 'leviathan', 'ramuh', 'shiva', 'odin', 'ultimaex', 'garudaex', 'titanex', 'ifritex', 'cancerex',
             'leviex', 'ramuhex', 'shivaex', 'dung80', 'dung70', 'dung60', 'dung50', 'leveling', 'hunt', 'fsh', 'other']
